GET http://localhost:6060/authors

#####

GET http://localhost:6060/authors/64b97e30a8221196137955df

#####

POST http://localhost:6060/authors HTTP/1.1
Content-Type: application/json

{
"name": "Prova",
"surname": "Prova",
"email": "prova1@gmail.com",
"password": "prova",
"birthdate": "06/06/1900",
"avatar": "a.jpg",
"role": "member"
}

#####

PATCH http://localhost:6060/authors/64aebd872fa8b79a27f23ab3 HTTP/1.1
Content-Type: application/json

{
    "name": "Matteone"
}

#####

DELETE http://localhost:6060/authors/64c3961587bf520cf66b4d77


#####
GET http://localhost:6060/authors/64b2e1a1b1b1c7ddda6256ac/blogPosts
